import { useReducer} from "react"
import DragDrop from "../components/Flashcards/DragDrop"
import { UploadButton } from "@/components/Buttons/UploadButton"
import { fileReducer, initialFileState } from "@/reducers/fileReducer"
import { DropDownList } from "@/components/Survey/DropDownList"
import { NUMBER_OF_FLASHCARDS } from "@/config/Constants"
import { PDFParser } from "@/components/Flashcards/PDFParser"
import { FetchQnA } from "@/components/Flashcards/FetchQnA"
import { QnAConverter } from "@/components/Flashcards/QnAConverter"
import { SwinButton } from "@/components/Buttons/SwinButton"
import { FaGamepad } from "react-icons/fa"

export const CreateFlashcard1 = () => {
    
    const [state, dispatch] = useReducer(fileReducer, initialFileState)
    
    const handleUpload = async (file: File) => {
        dispatch({ type: "SET_FILE", payload: file });
        try {
            const extractedText = await PDFParser(file);
            await dispatch({ type: "SET_EXTRACTED_TEXT", payload: extractedText });
            console.log("Extracted Text:", extractedText);
        } catch (error) {
            console.error("Error in Extraction of Text:", error);
        }
    };

    const handleSelect = (option: number)=>{
        dispatch ({type: "SET_FLASHCARD_COUNT", payload: option})
    };

    const handleGenerate = async ()=> { 
        try{
            const QnAText = await FetchQnA(state.extractedText, state.flashcardCount)
            console.log("QNA FROM MISTRAL:", QnAText)
            await dispatch ({type:"SET_QNA_TEXT", payload: QnAText})

            const QnAFormatted = QnAConverter(QnAText)
            console.log("Formatted QnA", QnAFormatted)

        }catch(error){
            console.log("Error in API call:", error)
        }
    };


    return (
        <>
            <div>
                <div>
                    <DragDrop onUpload ={handleUpload}/>
                    {state.file && (<div>Uploaded File:{} </div>)}
                </div>
                
                <div>
                    <UploadButton file={state.file} onUpload={handleUpload} label="Upload"  />
                </div>
                
                <div>
                    <label className="">Select Number of Flashcards</label>
                    <DropDownList options={NUMBER_OF_FLASHCARDS} handleClick={handleSelect} label="Number of Flashcards"/>
                </div>

                <div>
                    <SwinButton label = "Generate" onClick={handleGenerate} icon={<FaGamepad/>} />
                </div>

                <div>
                    <label>Question and Answers generated by Mistral</label>
                    {state.QnAText}
                </div>
            </div>
        </>
    )
}